package org.intercom.domain;

// Generated Jun 14, 2012 10:05:59 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Colonne generated by hbm2java
 */
@Entity
@Table(name = "COLONNE")
public class Colonne implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idColonne;
	private Colonne colonne;
	private StructureDonnees structureDonnees;
	private PolitiqueSubstitusion politiqueSubstitusion;
	private String nom;
	private BigDecimal typeDonnees;
	private BigDecimal longueur;
	private BigDecimal valeurMin;
	private BigDecimal valeurMax;
	private String valeurParDefaut;
	private BigDecimal ordreDansFichier;
	private BigDecimal nullable;
	private BigDecimal clePrimaire;
	private Set<Colonne> colonnes = new HashSet<Colonne>(0);

	public Colonne() {
	}

	public Colonne(BigDecimal idColonne, StructureDonnees structureDonnees) {
		this.idColonne = idColonne;
		this.structureDonnees = structureDonnees;
	}

	public Colonne(BigDecimal idColonne, Colonne colonne,
			StructureDonnees structureDonnees,
			PolitiqueSubstitusion politiqueSubstitusion, String nom,
			BigDecimal typeDonnees, BigDecimal longueur, BigDecimal valeurMin,
			BigDecimal valeurMax, String valeurParDefaut,
			BigDecimal ordreDansFichier, BigDecimal nullable,
			BigDecimal clePrimaire, Set<Colonne> colonnes) {
		this.idColonne = idColonne;
		this.colonne = colonne;
		this.structureDonnees = structureDonnees;
		this.politiqueSubstitusion = politiqueSubstitusion;
		this.nom = nom;
		this.typeDonnees = typeDonnees;
		this.longueur = longueur;
		this.valeurMin = valeurMin;
		this.valeurMax = valeurMax;
		this.valeurParDefaut = valeurParDefaut;
		this.ordreDansFichier = ordreDansFichier;
		this.nullable = nullable;
		this.clePrimaire = clePrimaire;
		this.colonnes = colonnes;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "COLONNE_SEQ_GEN")
	@SequenceGenerator(name = "COLONNE_SEQ_GEN", sequenceName = "COLONNE_SEQ")
	@Column(name = "ID_COLONNE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdColonne() {
		return this.idColonne;
	}

	public void setIdColonne(BigDecimal idColonne) {
		this.idColonne = idColonne;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_COLONNE_REFRENCE")
	public Colonne getColonne() {
		return this.colonne;
	}

	public void setColonne(Colonne colonne) {
		this.colonne = colonne;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_STRUCTURE_DONNEES", nullable = false)
	public StructureDonnees getStructureDonnees() {
		return this.structureDonnees;
	}

	public void setStructureDonnees(StructureDonnees structureDonnees) {
		this.structureDonnees = structureDonnees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_POL_SUBSTITUSION")
	public PolitiqueSubstitusion getPolitiqueSubstitusion() {
		return this.politiqueSubstitusion;
	}

	public void setPolitiqueSubstitusion(
			PolitiqueSubstitusion politiqueSubstitusion) {
		this.politiqueSubstitusion = politiqueSubstitusion;
	}

	@Column(name = "NOM", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "TYPE_DONNEES", precision = 22, scale = 0)
	public BigDecimal getTypeDonnees() {
		return this.typeDonnees;
	}

	public void setTypeDonnees(BigDecimal typeDonnees) {
		this.typeDonnees = typeDonnees;
	}

	@Column(name = "LONGUEUR", precision = 22, scale = 0)
	public BigDecimal getLongueur() {
		return this.longueur;
	}

	public void setLongueur(BigDecimal longueur) {
		this.longueur = longueur;
	}

	@Column(name = "VALEUR_MIN", precision = 22, scale = 0)
	public BigDecimal getValeurMin() {
		return this.valeurMin;
	}

	public void setValeurMin(BigDecimal valeurMin) {
		this.valeurMin = valeurMin;
	}

	@Column(name = "VALEUR_MAX", precision = 22, scale = 0)
	public BigDecimal getValeurMax() {
		return this.valeurMax;
	}

	public void setValeurMax(BigDecimal valeurMax) {
		this.valeurMax = valeurMax;
	}

	@Column(name = "VALEUR_PAR_DEFAUT", length = 45)
	public String getValeurParDefaut() {
		return this.valeurParDefaut;
	}

	public void setValeurParDefaut(String valeurParDefaut) {
		this.valeurParDefaut = valeurParDefaut;
	}

	@Column(name = "ORDRE_DANS_FICHIER", precision = 22, scale = 0)
	public BigDecimal getOrdreDansFichier() {
		return this.ordreDansFichier;
	}

	public void setOrdreDansFichier(BigDecimal ordreDansFichier) {
		this.ordreDansFichier = ordreDansFichier;
	}

	@Column(name = "NULLABLE", precision = 22, scale = 0)
	public BigDecimal getNullable() {
		return this.nullable;
	}

	public void setNullable(BigDecimal nullable) {
		this.nullable = nullable;
	}

	@Column(name = "CLE_PRIMAIRE", precision = 22, scale = 0)
	public BigDecimal getClePrimaire() {
		return this.clePrimaire;
	}

	public void setClePrimaire(BigDecimal clePrimaire) {
		this.clePrimaire = clePrimaire;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "colonne")
	public Set<Colonne> getColonnes() {
		return this.colonnes;
	}

	public void setColonnes(Set<Colonne> colonnes) {
		this.colonnes = colonnes;
	}

}
