package org.intercom.domain;

// Generated Jun 6, 2012 4:16:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ConnexionBd generated by hbm2java
 */
@Entity
@Table(name = "CONNEXION_BD")
public class ConnexionBd implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idConnexionBd;
	private Sgbd sgbd;
	private String nomConnexionBd;
	private String nomBaseDonnees;
	private String nomUtilisateur;
	private String motDePasse;
	private String urlConnexion;
	private Set<TableBd> tableBds = new HashSet<TableBd>(0);

	public ConnexionBd() {
	}

	public ConnexionBd(BigDecimal idConnexionBd) {
		this.idConnexionBd = idConnexionBd;
	}

	public ConnexionBd(BigDecimal idConnexionBd, Sgbd sgbd,
			String nomConnexionBd, String nomBaseDonnees,
			String nomUtilisateur, String motDePasse, String urlConnexion,
			Set<TableBd> tableBds) {
		this.idConnexionBd = idConnexionBd;
		this.sgbd = sgbd;
		this.nomConnexionBd = nomConnexionBd;
		this.nomBaseDonnees = nomBaseDonnees;
		this.nomUtilisateur = nomUtilisateur;
		this.motDePasse = motDePasse;
		this.urlConnexion = urlConnexion;
		this.tableBds = tableBds;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CONNEXION_BD_SEQ_GEN")
	@SequenceGenerator(name = "CONNEXION_BD_SEQ_GEN", sequenceName = "CONNEXION_BD_SEQ")
	@Column(name = "ID_CONNEXION_BD", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdConnexionBd() {
		return this.idConnexionBd;
	}

	public void setIdConnexionBd(BigDecimal idConnexionBd) {
		this.idConnexionBd = idConnexionBd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SGBD")
	public Sgbd getSgbd() {
		return this.sgbd;
	}

	public void setSgbd(Sgbd sgbd) {
		this.sgbd = sgbd;
	}

	@Column(name = "NOM_CONNEXION_BD", length = 20)
	public String getNomConnexionBd() {
		return this.nomConnexionBd;
	}

	public void setNomConnexionBd(String nomConnexionBd) {
		this.nomConnexionBd = nomConnexionBd;
	}

	@Column(name = "NOM_BASE_DONNEES", length = 20)
	public String getNomBaseDonnees() {
		return this.nomBaseDonnees;
	}

	public void setNomBaseDonnees(String nomBaseDonnees) {
		this.nomBaseDonnees = nomBaseDonnees;
	}

	@Column(name = "NOM_UTILISATEUR", length = 20)
	public String getNomUtilisateur() {
		return this.nomUtilisateur;
	}

	public void setNomUtilisateur(String nomUtilisateur) {
		this.nomUtilisateur = nomUtilisateur;
	}

	@Column(name = "MOT_DE_PASSE", length = 20)
	public String getMotDePasse() {
		return this.motDePasse;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}

	@Column(name = "URL_CONNEXION", length = 250)
	public String getUrlConnexion() {
		return this.urlConnexion;
	}

	public void setUrlConnexion(String urlConnexion) {
		this.urlConnexion = urlConnexion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "connexionBd")
	public Set<TableBd> getTableBds() {
		return this.tableBds;
	}

	public void setTableBds(Set<TableBd> tableBds) {
		this.tableBds = tableBds;
	}

}
