package org.intercom.domain;

// Generated Jun 6, 2012 4:16:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ConnexionFtp generated by hbm2java
 */
@Entity
@Table(name = "CONNEXION_FTP")
public class ConnexionFtp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public ConnexionFtp(String nomConnexionFtp, String adresseServeurFtp,
			String nomUtilisateur, String motDePasse, BigDecimal numeroPort) {
		super();
		this.nomConnexionFtp = nomConnexionFtp;
		this.adresseServeurFtp = adresseServeurFtp;
		this.nomUtilisateur = nomUtilisateur;
		this.motDePasse = motDePasse;
		this.numeroPort = numeroPort;
	}

	private BigDecimal id;
	private String nomConnexionFtp;
	private String adresseServeurFtp;
	private String nomUtilisateur;
	private String motDePasse;
	private BigDecimal numeroPort;

	public ConnexionFtp() {
	}

	public ConnexionFtp(BigDecimal id) {
		this.id = id;
	}

	public ConnexionFtp(BigDecimal id, String nomConnexionFtp,
			String adresseServeurFtp, String nomUtilisateur, String motDePasse,
			BigDecimal numeroPort) {
		this.id = id;
		this.nomConnexionFtp = nomConnexionFtp;
		this.adresseServeurFtp = adresseServeurFtp;
		this.nomUtilisateur = nomUtilisateur;
		this.motDePasse = motDePasse;
		this.numeroPort = numeroPort;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CONNEXION_FTP_SEQ_GEN")
	@SequenceGenerator(name = "CONNEXION_FTP_SEQ_GEN", sequenceName = "CONNEXION_FTP_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NOM_CONNEXION_FTP", length = 20)
	public String getNomConnexionFtp() {
		return this.nomConnexionFtp;
	}

	public void setNomConnexionFtp(String nomConnexionFtp) {
		this.nomConnexionFtp = nomConnexionFtp;
	}

	@Column(name = "ADRESSE_SERVEUR_FTP", length = 20)
	public String getAdresseServeurFtp() {
		return this.adresseServeurFtp;
	}

	public void setAdresseServeurFtp(String adresseServeurFtp) {
		this.adresseServeurFtp = adresseServeurFtp;
	}

	@Column(name = "NOM_UTILISATEUR", length = 20)
	public String getNomUtilisateur() {
		return this.nomUtilisateur;
	}

	public void setNomUtilisateur(String nomUtilisateur) {
		this.nomUtilisateur = nomUtilisateur;
	}

	@Column(name = "MOT_DE_PASSE", length = 20)
	public String getMotDePasse() {
		return this.motDePasse;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}

	@Column(name = "NUMERO_PORT", precision = 22, scale = 0)
	public BigDecimal getNumeroPort() {
		return this.numeroPort;
	}

	public void setNumeroPort(BigDecimal numeroPort) {
		this.numeroPort = numeroPort;
	}

}
