package org.intercom.domain;

// Generated Jun 6, 2012 4:16:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Correction generated by hbm2java
 */
@Entity
@Table(name = "CORRECTION")
public class Correction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idCorrection;
	private Date dateHeureCorrection;
	private Set<Erreur> erreurs = new HashSet<Erreur>(0);

	public Correction() {
	}

	public Correction(BigDecimal idCorrection) {
		this.idCorrection = idCorrection;
	}

	public Correction(BigDecimal idCorrection, Date dateHeureCorrection,
			Set<Erreur> erreurs) {
		this.idCorrection = idCorrection;
		this.dateHeureCorrection = dateHeureCorrection;
		this.erreurs = erreurs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CORRECTION_SEQ_GEN")
	@SequenceGenerator(name = "CORRECTION_SEQ_GEN", sequenceName = "CORRECTION_SEQ")
	@Column(name = "ID_CORRECTION", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdCorrection() {
		return this.idCorrection;
	}

	public void setIdCorrection(BigDecimal idCorrection) {
		this.idCorrection = idCorrection;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_HEURE_CORRECTION", length = 7)
	public Date getDateHeureCorrection() {
		return this.dateHeureCorrection;
	}

	public void setDateHeureCorrection(Date dateHeureCorrection) {
		this.dateHeureCorrection = dateHeureCorrection;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "correction")
	public Set<Erreur> getErreurs() {
		return this.erreurs;
	}

	public void setErreurs(Set<Erreur> erreurs) {
		this.erreurs = erreurs;
	}

}
