package org.intercom.domain;

// Generated Aug 7, 2012 1:25:42 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DroitUtilisateur generated by hbm2java
 */
@Entity
@Table(name = "DROIT_UTILISATEUR")
public class DroitUtilisateur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idDroitUtilisateur;
	private String label;
	private Set<DroitSysteme> droitSystemes = new HashSet<DroitSysteme> (0);
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur> (0);

	public DroitUtilisateur() {
	}

	public DroitUtilisateur(BigDecimal idDroitUtilisateur) {
		this.idDroitUtilisateur = idDroitUtilisateur;
	}

	public DroitUtilisateur(BigDecimal idDroitUtilisateur, String label,
			Set<DroitSysteme> droitSystemes, Set<Utilisateur> utilisateurs) {
		this.idDroitUtilisateur = idDroitUtilisateur;
		this.label = label;
		this.droitSystemes = droitSystemes;
		this.utilisateurs = utilisateurs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "DROIT_UTILISATEUR_SEQ_GEN")
	@SequenceGenerator(name = "DROIT_UTILISATEUR_SEQ_GEN", initialValue=2, sequenceName = "DROIT_UTILISATEUR_SEQ")
	@Column(name = "ID_DROIT_UTILISATEUR", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDroitUtilisateur() {
		return this.idDroitUtilisateur;
	}

	public void setIdDroitUtilisateur(BigDecimal idDroitUtilisateur) {
		this.idDroitUtilisateur = idDroitUtilisateur;
	}

	@Column(name = "LABEL", length = 250)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "DROIT_UTILISATEUR_SYSTEME", joinColumns = { @JoinColumn(name = "ID_DROIT_UTILSATEUR", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ID_DROIT_SYSTEME", nullable = false, updatable = false) })
	public Set<DroitSysteme> getDroitSystemes() {
		return this.droitSystemes;
	}

	public void setDroitSystemes(Set<DroitSysteme> droitSystemes) {
		this.droitSystemes = droitSystemes;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "UTILISATEUR_DROIT", joinColumns = { @JoinColumn(name = "DROITS_ID_DROITS", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "UTILISATEUR_ID_UTILISATEUR", nullable = false, updatable = false) })
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
