package org.intercom.domain;

// Generated Aug 7, 2012 1:25:42 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DroitSysteme generated by hbm2java
 */
@Entity
@Table(name = "DROIT_SYSTEME")
public class DroitSysteme implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idDroitSysteme;
	private String role;
	private String label;
	private Set<DroitUtilisateur> droitUtilisateurs = new HashSet<DroitUtilisateur>(0);

	public DroitSysteme() {
	}

	public DroitSysteme(BigDecimal idDroitSysteme) {
		this.idDroitSysteme = idDroitSysteme;
	}

	public DroitSysteme(BigDecimal idDroitSysteme, String role, String label,
			Set<DroitUtilisateur> droitUtilisateurs) {
		this.idDroitSysteme = idDroitSysteme;
		this.role = role;
		this.label = label;
		this.droitUtilisateurs = droitUtilisateurs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "DROIT_SYSTEME_SEQ_GEN")
	@SequenceGenerator(name = "DROIT_SYSTEME_SEQ_GEN", initialValue=2, sequenceName = "DROIT_SYSTEME_SEQ")
	@Column(name = "ID_DROIT_SYSTEME", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDroitSysteme() {
		return this.idDroitSysteme;
	}

	public void setIdDroitSysteme(BigDecimal idDroitSysteme) {
		this.idDroitSysteme = idDroitSysteme;
	}

	@Column(name = "ROLE", length = 100)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "LABEL", length = 250)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "DROIT_UTILISATEUR_SYSTEME", joinColumns = { @JoinColumn(name = "ID_DROIT_SYSTEME", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ID_DROIT_UTILSATEUR", nullable = false, updatable = false) })
	public Set<DroitUtilisateur> getDroitUtilisateurs() {
		return this.droitUtilisateurs;
	}

	public void setDroitUtilisateurs(Set<DroitUtilisateur> droitUtilisateurs) {
		this.droitUtilisateurs = droitUtilisateurs;
	}

}
