package org.intercom.domain;

// Generated Jun 6, 2012 4:16:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Erreur generated by hbm2java
 */
@Entity
@Table(name = "ERREUR")
public class Erreur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idErreur;
	private Fichier fichier;
	private Correction correction;
	private BigDecimal numLigne;
	private BigDecimal numColonne;
	private String type;

	public Erreur() {
	}

	public Erreur(BigDecimal idErreur, Fichier fichier) {
		this.idErreur = idErreur;
		this.fichier = fichier;
	}

	public Erreur(BigDecimal idErreur, Fichier fichier, Correction correction,
			BigDecimal numLigne, BigDecimal numColonne, String type) {
		this.idErreur = idErreur;
		this.fichier = fichier;
		this.correction = correction;
		this.numLigne = numLigne;
		this.numColonne = numColonne;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "ERREUR_SEQ_GEN")
	@SequenceGenerator(name = "ERREUR_SEQ_GEN", sequenceName = "ERREUR_SEQ")
	@Column(name = "ID_ERREUR", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdErreur() {
		return this.idErreur;
	}

	public void setIdErreur(BigDecimal idErreur) {
		this.idErreur = idErreur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FICHIER", nullable = false)
	public Fichier getFichier() {
		return this.fichier;
	}

	public void setFichier(Fichier fichier) {
		this.fichier = fichier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CORRECTION")
	public Correction getCorrection() {
		return this.correction;
	}

	public void setCorrection(Correction correction) {
		this.correction = correction;
	}

	@Column(name = "NUM_LIGNE", precision = 22, scale = 0)
	public BigDecimal getNumLigne() {
		return this.numLigne;
	}

	public void setNumLigne(BigDecimal numLigne) {
		this.numLigne = numLigne;
	}

	@Column(name = "NUM_COLONNE", precision = 22, scale = 0)
	public BigDecimal getNumColonne() {
		return this.numColonne;
	}

	public void setNumColonne(BigDecimal numColonne) {
		this.numColonne = numColonne;
	}

	@Column(name = "TYPE", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
