package org.intercom.domain;

// Generated Jun 11, 2012 10:32:19 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Fichier generated by hbm2java
 */
@Entity
@Table(name = "FICHIER")
public class Fichier implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idFichier;
	private String nom;
	private String chemin;
	private Set<Erreur> erreurs = new HashSet<Erreur>(0);

	public Fichier() {
	}

	public Fichier(BigDecimal idFichier) {
		this.idFichier = idFichier;
	}

	public Fichier(BigDecimal idFichier, String nom, String chemin,
			Set<Erreur> erreurs) {
		this.idFichier = idFichier;
		this.nom = nom;
		this.chemin = chemin;
		this.erreurs = erreurs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "FICHIER_SEQ_GEN")
	@SequenceGenerator(name = "FICHIER_SEQ_GEN", sequenceName = "FICHIER_SEQ")
	@Column(name = "ID_FICHIER", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdFichier() {
		return this.idFichier;
	}

	public void setIdFichier(BigDecimal idFichier) {
		this.idFichier = idFichier;
	}

	@Column(name = "NOM", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "CHEMIN", length = 260)
	public String getChemin() {
		return this.chemin;
	}

	public void setChemin(String chemin) {
		this.chemin = chemin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichier")
	public Set<Erreur> getErreurs() {
		return this.erreurs;
	}

	public void setErreurs(Set<Erreur> erreurs) {
		this.erreurs = erreurs;
	}

}
