package org.intercom.domain;

// Generated Jun 6, 2012 4:16:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ParametreApplication generated by hbm2java
 */
@Entity
@Table(name = "PARAMETRE_APPLICATION")
public class ParametreApplication implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idParametreApplication;
	private BigDecimal tailleHistoriqueMemoire;

	public ParametreApplication() {
	}

	public ParametreApplication(BigDecimal idParametreApplication) {
		this.idParametreApplication = idParametreApplication;
	}

	public ParametreApplication(BigDecimal idParametreApplication,
			BigDecimal tailleHistoriqueMemoire) {
		this.idParametreApplication = idParametreApplication;
		this.tailleHistoriqueMemoire = tailleHistoriqueMemoire;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "PARAMETRE_APPLICATION_SEQ_GEN")
	@SequenceGenerator(name = "PARAMETRE_APPLICATION_SEQ_GEN", sequenceName = "PARAMETRE_APPLICATION_SEQ")
	@Column(name = "ID_PARAMETRE_APPLICATION", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdParametreApplication() {
		return this.idParametreApplication;
	}

	public void setIdParametreApplication(BigDecimal idParametreApplication) {
		this.idParametreApplication = idParametreApplication;
	}

	@Column(name = "TAILLE_HISTORIQUE_MEMOIRE", precision = 22, scale = 0)
	public BigDecimal getTailleHistoriqueMemoire() {
		return this.tailleHistoriqueMemoire;
	}

	public void setTailleHistoriqueMemoire(BigDecimal tailleHistoriqueMemoire) {
		this.tailleHistoriqueMemoire = tailleHistoriqueMemoire;
	}

}
