package org.intercom.domain;

// Generated Jun 6, 2012 4:16:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Parametres generated by hbm2java
 */
@Entity
@Table(name = "PARAMETRES")
public class Parametres implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String nom;
	private String label;
	private BigDecimal valeur;

	public Parametres() {
	}

	public Parametres(BigDecimal id) {
		this.id = id;
	}

	public Parametres(BigDecimal id, String nom, String label, BigDecimal valeur) {
		this.id = id;
		this.nom = nom;
		this.label = label;
		this.valeur = valeur;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "PARAMETRES_SEQ_GEN")
	@SequenceGenerator(name = "PARAMETRES_SEQ_GEN", sequenceName = "PARAMETRES_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NOM", length = 20)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "LABEL", length = 20)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "VALEUR", precision = 22, scale = 0)
	public BigDecimal getValeur() {
		return this.valeur;
	}

	public void setValeur(BigDecimal valeur) {
		this.valeur = valeur;
	}

}
