package org.intercom.domain;

// Generated Jun 6, 2012 4:16:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PolitiqueSubstitusion generated by hbm2java
 */
@Entity
@Table(name = "POLITIQUE_SUBSTITUSION")
public class PolitiqueSubstitusion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idPolitiqueSubstitusion;
	private String valeurOrigine;
	private String valeurNouveau;
	private Set<Colonne> colonnes = new HashSet<Colonne>(0);

	public PolitiqueSubstitusion() {
	}

	public PolitiqueSubstitusion(BigDecimal idPolitiqueSubstitusion) {
		this.idPolitiqueSubstitusion = idPolitiqueSubstitusion;
	}

	public PolitiqueSubstitusion(BigDecimal idPolitiqueSubstitusion,
			String valeurOrigine, String valeurNouveau, Set<Colonne> colonnes) {
		this.idPolitiqueSubstitusion = idPolitiqueSubstitusion;
		this.valeurOrigine = valeurOrigine;
		this.valeurNouveau = valeurNouveau;
		this.colonnes = colonnes;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "POLITIQUE_SUBSTITUSION_SEQ_GEN")
	@SequenceGenerator(name = "POLITIQUE_SUBSTITUSION_SEQ_GEN", sequenceName = "POLITIQUE_SUBSTITUSION_SEQ")
	@Column(name = "ID_POLITIQUE_SUBSTITUSION", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdPolitiqueSubstitusion() {
		return this.idPolitiqueSubstitusion;
	}

	public void setIdPolitiqueSubstitusion(BigDecimal idPolitiqueSubstitusion) {
		this.idPolitiqueSubstitusion = idPolitiqueSubstitusion;
	}

	@Column(name = "VALEUR_ORIGINE", length = 45)
	public String getValeurOrigine() {
		return this.valeurOrigine;
	}

	public void setValeurOrigine(String valeurOrigine) {
		this.valeurOrigine = valeurOrigine;
	}

	@Column(name = "VALEUR_NOUVEAU", length = 45)
	public String getValeurNouveau() {
		return this.valeurNouveau;
	}

	public void setValeurNouveau(String valeurNouveau) {
		this.valeurNouveau = valeurNouveau;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "politiqueSubstitusion")
	public Set<Colonne> getColonnes() {
		return this.colonnes;
	}

	public void setColonnes(Set<Colonne> colonnes) {
		this.colonnes = colonnes;
	}

}
