package org.intercom.domain;

// Generated Jun 6, 2012 4:16:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SauveguardeTable generated by hbm2java
 */
@Entity
@Table(name = "SAUVEGUARDE_TABLE")
public class SauveguardeTable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idSauveguardeTable;
	private TableBd tableBd;
	private Date dateHeureSauveguarde;
	private String cheminFichierSauveguarde;

	public SauveguardeTable() {
	}

	public SauveguardeTable(BigDecimal idSauveguardeTable, TableBd tableBd) {
		this.idSauveguardeTable = idSauveguardeTable;
		this.tableBd = tableBd;
	}

	public SauveguardeTable(BigDecimal idSauveguardeTable, TableBd tableBd,
			Date dateHeureSauveguarde, String cheminFichierSauveguarde) {
		this.idSauveguardeTable = idSauveguardeTable;
		this.tableBd = tableBd;
		this.dateHeureSauveguarde = dateHeureSauveguarde;
		this.cheminFichierSauveguarde = cheminFichierSauveguarde;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "SAUVEGUARDE_TABLE_SEQ_GEN")
	@SequenceGenerator(name = "SAUVEGUARDE_TABLE_SEQ_GEN", sequenceName = "SAUVEGUARDE_TABLE_SEQ")
	@Column(name = "ID_SAUVEGUARDE_TABLE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdSauveguardeTable() {
		return this.idSauveguardeTable;
	}

	public void setIdSauveguardeTable(BigDecimal idSauveguardeTable) {
		this.idSauveguardeTable = idSauveguardeTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TABLE", nullable = false)
	public TableBd getTableBd() {
		return this.tableBd;
	}

	public void setTableBd(TableBd tableBd) {
		this.tableBd = tableBd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_HEURE_SAUVEGUARDE", length = 7)
	public Date getDateHeureSauveguarde() {
		return this.dateHeureSauveguarde;
	}

	public void setDateHeureSauveguarde(Date dateHeureSauveguarde) {
		this.dateHeureSauveguarde = dateHeureSauveguarde;
	}

	@Column(name = "CHEMIN_FICHIER_SAUVEGUARDE", length = 45)
	public String getCheminFichierSauveguarde() {
		return this.cheminFichierSauveguarde;
	}

	public void setCheminFichierSauveguarde(String cheminFichierSauveguarde) {
		this.cheminFichierSauveguarde = cheminFichierSauveguarde;
	}

}
