package org.intercom.domain;

// Generated Jun 6, 2012 4:16:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SelectionParIntervalle generated by hbm2java
 */
@Entity
@Table(name = "SELECTION_PAR_INTERVALLE")
public class SelectionParIntervalle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idSelection;
	private Configuration configuration;
	private BigDecimal numLigneDepart;
	private BigDecimal numLigneFin;

	public SelectionParIntervalle() {
	}

	public SelectionParIntervalle(BigDecimal idSelection) {
		this.idSelection = idSelection;
	}

	public SelectionParIntervalle(BigDecimal idSelection,
			Configuration configuration, BigDecimal numLigneDepart,
			BigDecimal numLigneFin) {
		this.idSelection = idSelection;
		this.configuration = configuration;
		this.numLigneDepart = numLigneDepart;
		this.numLigneFin = numLigneFin;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "SELECTION_PAR_INTERVALLE_SEQ_GEN")
	@SequenceGenerator(name = "SELECTION_PAR_INTERVALLE_SEQ_GEN", sequenceName = "SELECTION_PAR_INTERVALLE_SEQ")
	@Column(name = "ID_SELECTION", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdSelection() {
		return this.idSelection;
	}

	public void setIdSelection(BigDecimal idSelection) {
		this.idSelection = idSelection;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CONFIGURATION")
	public Configuration getConfiguration() {
		return this.configuration;
	}

	public void setConfiguration(Configuration configuration) {
		this.configuration = configuration;
	}

	@Column(name = "NUM_LIGNE_DEPART", precision = 22, scale = 0)
	public BigDecimal getNumLigneDepart() {
		return this.numLigneDepart;
	}

	public void setNumLigneDepart(BigDecimal numLigneDepart) {
		this.numLigneDepart = numLigneDepart;
	}

	@Column(name = "NUM_LIGNE_FIN", precision = 22, scale = 0)
	public BigDecimal getNumLigneFin() {
		return this.numLigneFin;
	}

	public void setNumLigneFin(BigDecimal numLigneFin) {
		this.numLigneFin = numLigneFin;
	}

}
