package org.intercom.domain;

// Generated Jul 10, 2012 1:42:37 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Sgbd generated by hbm2java
 */
@Entity
@Table(name = "SGBD")
public class Sgbd implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idSgbd;
	private String type;
	private String driverClassName;
	private String fichierDriverJar;
	private Set<ConnexionBd> connexionBds = new HashSet<ConnexionBd>(0);

	public Sgbd() {
	}

	public Sgbd(BigDecimal idSgbd) {
		this.idSgbd = idSgbd;
	}

	public Sgbd(BigDecimal idSgbd, String type, String driverClassName,
			String fichierDriverJar, Set<ConnexionBd> connexionBds) {
		this.idSgbd = idSgbd;
		this.type = type;
		this.driverClassName = driverClassName;
		this.fichierDriverJar = fichierDriverJar;
		this.connexionBds = connexionBds;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "SGBD_SEQ_GEN")
	@SequenceGenerator(name = "SGBD_SEQ_GEN", sequenceName = "SGBD_SEQ")
	@Column(name = "ID_SGBD", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdSgbd() {
		return this.idSgbd;
	}

	public void setIdSgbd(BigDecimal idSgbd) {
		this.idSgbd = idSgbd;
	}

	@Column(name = "TYPE", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "DRIVER_CLASS_NAME", length = 260)
	public String getDriverClassName() {
		return this.driverClassName;
	}

	public void setDriverClassName(String driverClassName) {
		this.driverClassName = driverClassName;
	}

	@Column(name = "FICHIER_DRIVER_JAR", length = 260)
	public String getFichierDriverJar() {
		return this.fichierDriverJar;
	}

	public void setFichierDriverJar(String fichierDriverJar) {
		this.fichierDriverJar = fichierDriverJar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgbd")
	public Set<ConnexionBd> getConnexionBds() {
		return this.connexionBds;
	}

	public void setConnexionBds(Set<ConnexionBd> connexionBds) {
		this.connexionBds = connexionBds;
	}

}
