package org.intercom.domain;

// Generated Jun 11, 2012 10:32:19 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * StructureDonnees generated by hbm2java
 */
@Entity
@Table(name = "STRUCTURE_DONNEES")
public class StructureDonnees implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idStructureDonnees;
	private String nom;
	private Set<Colonne> colonnes = new HashSet<Colonne>(0);
	private Set<TableBd> tableBds = new HashSet<TableBd>(0);

	public StructureDonnees() {
	}

	public StructureDonnees(BigDecimal idStructureDonnees) {
		this.idStructureDonnees = idStructureDonnees;
	}

	public StructureDonnees(BigDecimal idStructureDonnees, String nom,
			Set<Colonne> colonnes, Set<TableBd> tableBds) {
		this.idStructureDonnees = idStructureDonnees;
		this.nom = nom;
		this.colonnes = colonnes;
		this.tableBds = tableBds;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "STRUCTURE_DONNEES_SEQ_GEN")
	@SequenceGenerator(name = "STRUCTURE_DONNEES_SEQ_GEN", sequenceName = "STRUCTURE_DONNEES_SEQ")
	@Column(name = "ID_STRUCTURE_DONNEES", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdStructureDonnees() {
		return this.idStructureDonnees;
	}

	public void setIdStructureDonnees(BigDecimal idStructureDonnees) {
		this.idStructureDonnees = idStructureDonnees;
	}

	@Column(name = "NOM", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "structureDonnees")
	public Set<Colonne> getColonnes() {
		return this.colonnes;
	}

	public void setColonnes(Set<Colonne> colonnes) {
		this.colonnes = colonnes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "structureDonnees")
	public Set<TableBd> getTableBds() {
		return this.tableBds;
	}

	public void setTableBds(Set<TableBd> tableBds) {
		this.tableBds = tableBds;
	}

}
