package org.intercom.domain;

// Generated Jun 6, 2012 4:16:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TableBd generated by hbm2java
 */
@Entity
@Table(name = "TABLE_BD")
public class TableBd implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idTable;
	private ConnexionBd connexionBd;
	private StructureDonnees structureDonnees;
	private String nom;
	private Set<SauveguardeTable> sauveguardeTables = new HashSet<SauveguardeTable>(
			0);

	public TableBd() {
	}

	public TableBd(BigDecimal idTable, ConnexionBd connexionBd,
			StructureDonnees structureDonnees) {
		this.idTable = idTable;
		this.connexionBd = connexionBd;
		this.structureDonnees = structureDonnees;
	}

	public TableBd(BigDecimal idTable, ConnexionBd connexionBd,
			StructureDonnees structureDonnees, String nom,
			Set<SauveguardeTable> sauveguardeTables) {
		this.idTable = idTable;
		this.connexionBd = connexionBd;
		this.structureDonnees = structureDonnees;
		this.nom = nom;
		this.sauveguardeTables = sauveguardeTables;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "TABLE_BD_SEQ_GEN")
	@SequenceGenerator(name = "TABLE_BD_SEQ_GEN", sequenceName = "TABLE_BD_SEQ")
	@Column(name = "ID_TABLE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTable() {
		return this.idTable;
	}

	public void setIdTable(BigDecimal idTable) {
		this.idTable = idTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CONNEXION_BD", nullable = false)
	public ConnexionBd getConnexionBd() {
		return this.connexionBd;
	}

	public void setConnexionBd(ConnexionBd connexionBd) {
		this.connexionBd = connexionBd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_STRUCTURE_DONNEES", nullable = false)
	public StructureDonnees getStructureDonnees() {
		return this.structureDonnees;
	}

	public void setStructureDonnees(StructureDonnees structureDonnees) {
		this.structureDonnees = structureDonnees;
	}

	@Column(name = "NOM", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tableBd")
	public Set<SauveguardeTable> getSauveguardeTables() {
		return this.sauveguardeTables;
	}

	public void setSauveguardeTables(Set<SauveguardeTable> sauveguardeTables) {
		this.sauveguardeTables = sauveguardeTables;
	}

}
