package org.intercom.domain;

// Generated Aug 7, 2012 1:25:42 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "UTILISATEUR")
public class Utilisateur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idUtilisateur;
	private String nom;
	private String prenom;
	private String login;
	private String motDePasse;
	private Set<DroitUtilisateur> droitUtilisateurs = new HashSet<DroitUtilisateur>(0);

	public Utilisateur() {
	}

	public Utilisateur(BigDecimal idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public Utilisateur(BigDecimal idUtilisateur, String nom, String prenom,
			String login, String motDePasse, Set<DroitUtilisateur> droitUtilisateurs) {
		this.idUtilisateur = idUtilisateur;
		this.nom = nom;
		this.prenom = prenom;
		this.login = login;
		this.motDePasse = motDePasse;
		this.droitUtilisateurs = droitUtilisateurs;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "UTILISATEUR_SEQ_GEN")
	@SequenceGenerator(name = "UTILISATEUR_SEQ_GEN", initialValue=2, sequenceName = "UTILISATEUR_SEQ")
	@Column(name = "ID_UTILISATEUR", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(BigDecimal idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "NOM", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", length = 45)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "LOGIN", length = 45)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "MOT_DE_PASSE", length = 45)
	public String getMotDePasse() {
		return this.motDePasse;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "UTILISATEUR_DROIT", joinColumns = { @JoinColumn(name = "UTILISATEUR_ID_UTILISATEUR", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "DROITS_ID_DROITS", nullable = false, updatable = false) })
	public Set<DroitUtilisateur> getDroitUtilisateurs() {
		return this.droitUtilisateurs;
	}

	public void setDroitUtilisateurs(Set<DroitUtilisateur> droitUtilisateurs) {
		this.droitUtilisateurs = droitUtilisateurs;
	}

}
